"""Generate both ends of the PC ↔ Pico wire contract from the .toml beside them.

    pixi run gen-protocol            # rewrite the generated files
    pixi run gen-protocol --check    # fail if they have drifted (CI / pre-flash)

WHY A GENERATOR AND NOT A SHARED HEADER PARSED AT RUNTIME.

The C side cannot read a .toml, so the numbers must reach it as #defines one
way or another. The reverse — make protocol.h the source and have Python parse
it — was the tempting shortcut, and it is worse for one reason: a #define
cannot express the STRUCT FORMAT. Python's `struct.pack('<BhhBHH', ...)` for
MOVE_CLICK and the firmware's `pos + 10 > cdc_len` are the same fact stated in
two notations, and a header can only carry the second. Generating both from a
field list means the format string and the length are DERIVED from one list of
types, so they cannot disagree even in principle.

The generated files are COMMITTED. The Pico build must not need Python in its
toolchain, and a fresh clone must compile. That trade buys one hazard back —
a generated file can go stale — which is exactly what --check exists to catch.

⚠ THE GENERATED FILES ARE NOT THE SOURCE. Editing protocol.h or the
__init__.py beside it directly appears to work, survives a flash, and is then silently
reverted by the next person who runs this script. Both carry a DO-NOT-EDIT
banner naming this file, and --check turns the revert into a failure that
happens before the flash rather than after.
"""

import argparse
import os
import sys
import textwrap
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'press', 'protocol', 'protocol.toml')
OUT_H = os.path.join(ROOT, 'press', 'protocol', 'protocol.h')
OUT_PY = os.path.join(ROOT, 'press', 'protocol', '__init__.py')

# type -> (struct char, width in bytes, C type)
#
# ⚠ A FOURTH COLUMN OF C READER EXPRESSIONS STOOD HERE with seven lines
# justifying it, and nothing ever read it: the firmware still decodes its own
# fields by hand, and render_h() built C type names from a separate inline
# dict. Generating those readers is a real option, but it was not taken -- so
# the table described an intention rather than the output, which is the kind
# of comment that outlives its subject. The C type name it DID need is folded
# in here, so there is one table again instead of two.
TYPES = {
    'u8':  ('B', 1, 'uint8_t'),
    'i8':  ('b', 1, 'int8_t'),
    'u16': ('H', 2, 'uint16_t'),
    'i16': ('h', 2, 'int16_t'),
}

BANNER_LINES = [
    'GENERATED BY tools/gen_protocol.py — DO NOT EDIT.',
    '',
    'Source of truth: press/protocol/protocol.toml',
    'Regenerate:      pixi run gen-protocol',
    'Verify:          pixi run gen-protocol --check',
]


def load():
    with open(SOURCE, 'rb') as f:
        spec = tomllib.load(f)
    point_size = sum(TYPES[f['type']][1] for f in spec['pattern']['point_fields'])
    for cmd in spec['command']:
        # +1 for the opcode byte itself, so *_LEN is directly "bytes that must
        # be buffered before this command can be parsed".
        cmd['len'] = 1 + sum(TYPES[f['type']][1] for f in cmd['fields'])
        cmd['fmt'] = '<B' + ''.join(TYPES[f['type']][0] for f in cmd['fields'])
    spec['pattern']['point_size'] = point_size
    spec['pattern']['point_fmt'] = '<' + ''.join(
        TYPES[f['type']][0] for f in spec['pattern']['point_fields'])
    return spec


def _wrap_doc(doc, width=76):
    """Reflow a doc string into comment lines, keeping explicit newlines.

    ⚠ THIS WAS A HAND-ROLLED textwrap.wrap CARRYING A DEAD `prefix` PARAMETER.
    Both call sites passed '', which degraded every `line != prefix.rstrip()`
    in it to `line != ''`. tools/check_params.py is the ratchet for exactly
    that -- a parameter every caller pins to one value -- but its DIRS does
    not include tools/, a blind spot tools/CLAUDE.md names. Verified against
    all 13 docs before the swap: identical output, line for line.
    """
    out = []
    for para in doc.strip().split('\n'):
        out.extend(textwrap.wrap(para, width) or [''])
    return out


def render_h(spec):
    L = ['/* ' + BANNER_LINES[0]]
    L += [' * ' + b if b else ' *' for b in BANNER_LINES[1:]]
    L += [' */', '', '#ifndef PROTOCOL_H_', '#define PROTOCOL_H_', '',
          '#include <stdint.h>', '',
          f'#define PROTOCOL_VERSION {spec["meta"]["version"]}', '']

    pat = spec['pattern']
    L += ['/* ── Recoil pattern storage ─────────────────────────────── */',
          f'#define MAX_PATTERN_POINTS {pat["max_points"]}',
          f'#define PATTERN_POINT_SIZE {pat["point_size"]}', '',
          'typedef struct {']
    for f in pat['point_fields']:
        L.append(f'    {TYPES[f["type"]][2]:<9}{f["name"]};')
    L += ['} pattern_point_t;', '',
          '/* ── Commands (PC → Pico over CDC) ──────────────────────── */',
          '/* Every CMD_*_LEN counts the opcode byte, so it is the number of',
          ' * bytes that must be buffered before the command can be parsed. */',
          '']

    for cmd in spec['command']:
        for i, line in enumerate(_wrap_doc(cmd['doc'])):
            L.append(('/* ' if i == 0 else ' * ') + line)
        if cmd.get('reply'):
            L.append(f' * Reply: {cmd["reply"]}')
        if cmd.get('variable_payload'):
            L.append(f' * Then: {cmd["variable_payload"]} more bytes'
                     ' (LEN below is the HEADER only).')
        L.append(' */')
        L.append(f'#define CMD_{cmd["name"]:<18} 0x{cmd["opcode"]:02X}')
        L.append(f'#define CMD_{cmd["name"] + "_LEN":<18} {cmd["len"]}')
        L.append('')

    L += ['#endif  /* PROTOCOL_H_ */', '']
    return '\n'.join(L)


def render_py(spec):
    L = ['"""' + BANNER_LINES[0], '']
    L += BANNER_LINES[1:]
    L += ['"""', '', 'import struct', '',
          f'PROTOCOL_VERSION = {spec["meta"]["version"]}', '']

    pat = spec['pattern']
    L += ['# ── Recoil pattern storage ──────────────────────────────────',
          '# ⚠ The firmware CLAMPS an upload to MAX_PATTERN_POINTS rather than',
          '# rejecting it, so exceeding this loses knots with no error.',
          f'MAX_PATTERN_POINTS = {pat["max_points"]}',
          f'PATTERN_POINT_SIZE = {pat["point_size"]}',
          f'PATTERN_POINT_FMT = {pat["point_fmt"]!r}   '
          f'# {", ".join(f["name"] for f in pat["point_fields"])}',
          '',
          '# ── Commands (PC → Pico over CDC) ───────────────────────────',
          '# CMD_*_FMT packs the opcode as its first field, so:',
          "#     mouse.write(struct.pack(CMD_MOVE_FMT, CMD_MOVE, dx, dy))",
          '# CMD_*_LEN is that format\'s size, i.e. what the firmware waits for.',
          '']

    for cmd in spec['command']:
        for line in _wrap_doc(cmd['doc']):
            L.append('# ' + line)
        if cmd.get('reply'):
            L.append(f'# Reply: {cmd["reply"]}')
        if cmd.get('variable_payload'):
            L.append(f'# Then: {cmd["variable_payload"]} more bytes'
                     ' (FMT/LEN below are the HEADER only).')
        L.append(f'CMD_{cmd["name"]} = 0x{cmd["opcode"]:02X}')
        L.append(f'CMD_{cmd["name"]}_FMT = {cmd["fmt"]!r}')
        L.append(f'CMD_{cmd["name"]}_LEN = {cmd["len"]}')
        L.append('')

    # A generated self-check costs one import and removes the whole class of
    # "the table says 5 but struct says 4" bug from review.
    L += ['# The two derived views of the same field list must agree. If this',
          '# ever fires, tools/gen_protocol.py TYPES is wrong, not this file.',
          'for _n, _f, _l in [']
    for cmd in spec['command']:
        L.append(f'    ({cmd["name"]!r}, CMD_{cmd["name"]}_FMT,'
                 f' CMD_{cmd["name"]}_LEN),')
    L += ['        ]:',
          '    assert struct.calcsize(_f) == _l, (_n, _f, _l)',
          'assert struct.calcsize(PATTERN_POINT_FMT) == PATTERN_POINT_SIZE',
          'del _n, _f, _l', '']
    return '\n'.join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--check', action='store_true',
                    help='exit 1 if a generated file is out of date')
    args = ap.parse_args()

    spec = load()
    want = {OUT_H: render_h(spec), OUT_PY: render_py(spec)}

    stale = []
    for path, text in want.items():
        rel = os.path.relpath(path, ROOT).replace('\\', '/')
        try:
            with open(path, encoding='utf-8') as f:
                current = f.read()
        except OSError:
            current = None
        if current == text:
            print(f'ok      {rel}')
            continue
        if args.check:
            stale.append(rel)
            print(f'STALE   {rel}')
        else:
            with open(path, 'w', encoding='utf-8', newline='\n') as f:
                f.write(text)
            print(f'wrote   {rel}')

    if stale:
        print(f'\n{len(stale)} generated file(s) do not match protocol/'
              'protocol.toml.\nRun: pixi run gen-protocol', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
