"""GENERATED BY tools/gen_protocol.py — DO NOT EDIT.


Source of truth: press/protocol/protocol.toml
Regenerate:      pixi run gen-protocol
Verify:          pixi run gen-protocol --check
"""

import struct

PROTOCOL_VERSION = 1

# ── Recoil pattern storage ──────────────────────────────────
# ⚠ The firmware CLAMPS an upload to MAX_PATTERN_POINTS rather than
# rejecting it, so exceeding this loses knots with no error.
MAX_PATTERN_POINTS = 300
PATTERN_POINT_SIZE = 6
PATTERN_POINT_FMT = '<hhH'   # dx, dy, t_ms

# ── Commands (PC → Pico over CDC) ───────────────────────────
# CMD_*_FMT packs the opcode as its first field, so:
#     mouse.write(struct.pack(CMD_MOVE_FMT, CMD_MOVE, dx, dy))
# CMD_*_LEN is that format's size, i.e. what the firmware waits for.

# Replace the stored recoil curve. Clamped to MAX_PATTERN_POINTS.
# Then: count * PATTERN_POINT_SIZE more bytes (FMT/LEN below are the HEADER only).
CMD_PATTERN_UPLOAD = 0x10
CMD_PATTERN_UPLOAD_FMT = '<BH'
CMD_PATTERN_UPLOAD_LEN = 3

# Drop the stored curve. Recoil compensation emits nothing until re-uploaded.
CMD_PATTERN_CLEAR = 0x11
CMD_PATTERN_CLEAR_FMT = '<B'
CMD_PATTERN_CLEAR_LEN = 1

# Gate compensation without discarding the curve. This is the difference
# between a run that measures RAW recoil and one that measures the residual.
CMD_RECOIL_ENABLE = 0x12
CMD_RECOIL_ENABLE_FMT = '<BB'
CMD_RECOIL_ENABLE_LEN = 2

# Add to the mouse accumulator; emitted on the next HID report.
CMD_MOVE = 0x13
CMD_MOVE_FMT = '<Bhh'
CMD_MOVE_LEN = 5

# Hold `buttons` for `duration_ms`, starting now.
CMD_CLICK = 0x14
CMD_CLICK_FMT = '<BBH'
CMD_CLICK_LEN = 4

# Move now, then click after `delay_ms` for `duration_ms`. One command rather
# than two so the gap is timed on the Pico, not across USB.
CMD_MOVE_CLICK = 0x15
CMD_MOVE_CLICK_FMT = '<BhhBHH'
CMD_MOVE_CLICK_LEN = 10

# Suppress the human's real left click; only injected clicks fire. Zeroes the
# aim delta.
CMD_AIM_MODE = 0x16
CMD_AIM_MODE_FMT = '<BB'
CMD_AIM_MODE_LEN = 2

# Latest aim correction, sent by the PC once per frame.
CMD_SET_DELTA = 0x17
CMD_SET_DELTA_FMT = '<Bhh'
CMD_SET_DELTA_LEN = 5

# Tap a key on the Pico's second (keyboard) HID interface. `keycode` is a USB
# HID usage ID, forwarded uninterpreted — see press/pico_mouse.py HID_KEY_*.
CMD_KEY = 0x18
CMD_KEY_FMT = '<BBH'
CMD_KEY_LEN = 4

# Report the curve as STORED, plus the duration each bullet is spread over. A
# readback exists because measuring the firmware through the game is a closed
# loop: a systematic error in here gets absorbed into the fitted curve and the
# residual comes out clean. Two real bugs lived behind a clean residual.
# Reply: [pat] lines
CMD_PATTERN_READ = 0x19
CMD_PATTERN_READ_FMT = '<B'
CMD_PATTERN_READ_LEN = 1

# Run the real per-bullet maths `iters` times over the stored pattern and
# report commanded-vs-emitted totals. Touches no HID output, so it runs on a
# bench with no game — which is what makes it cheap enough for every flash.
# Reply: [sim] line
CMD_RECOIL_SIM = 0x1A
CMD_RECOIL_SIM_FMT = '<BH'
CMD_RECOIL_SIM_LEN = 3

# The mouse's own answer to the polling-rate SET, verbatim and undecoded — the
# decode is the thing in doubt.
# Reply: [razer] line
CMD_RAZER_READ = 0x1B
CMD_RAZER_READ_FMT = '<B'
CMD_RAZER_READ_LEN = 1

# Reboot into the ROM bootloader so flash.py can write a .uf2 without the
# BOOTSEL button. ⚠ If the running firmware is already broken this will not
# answer, and the board must be re-plugged with BOOTSEL held.
CMD_REBOOT_BOOTSEL = 0xFF
CMD_REBOOT_BOOTSEL_FMT = '<B'
CMD_REBOOT_BOOTSEL_LEN = 1

# The two derived views of the same field list must agree. If this
# ever fires, tools/gen_protocol.py TYPES is wrong, not this file.
for _n, _f, _l in [
    ('PATTERN_UPLOAD', CMD_PATTERN_UPLOAD_FMT, CMD_PATTERN_UPLOAD_LEN),
    ('PATTERN_CLEAR', CMD_PATTERN_CLEAR_FMT, CMD_PATTERN_CLEAR_LEN),
    ('RECOIL_ENABLE', CMD_RECOIL_ENABLE_FMT, CMD_RECOIL_ENABLE_LEN),
    ('MOVE', CMD_MOVE_FMT, CMD_MOVE_LEN),
    ('CLICK', CMD_CLICK_FMT, CMD_CLICK_LEN),
    ('MOVE_CLICK', CMD_MOVE_CLICK_FMT, CMD_MOVE_CLICK_LEN),
    ('AIM_MODE', CMD_AIM_MODE_FMT, CMD_AIM_MODE_LEN),
    ('SET_DELTA', CMD_SET_DELTA_FMT, CMD_SET_DELTA_LEN),
    ('KEY', CMD_KEY_FMT, CMD_KEY_LEN),
    ('PATTERN_READ', CMD_PATTERN_READ_FMT, CMD_PATTERN_READ_LEN),
    ('RECOIL_SIM', CMD_RECOIL_SIM_FMT, CMD_RECOIL_SIM_LEN),
    ('RAZER_READ', CMD_RAZER_READ_FMT, CMD_RAZER_READ_LEN),
    ('REBOOT_BOOTSEL', CMD_REBOOT_BOOTSEL_FMT, CMD_REBOOT_BOOTSEL_LEN),
        ]:
    assert struct.calcsize(_f) == _l, (_n, _f, _l)
assert struct.calcsize(PATTERN_POINT_FMT) == PATTERN_POINT_SIZE
del _n, _f, _l
