/* GENERATED BY tools/gen_protocol.py — DO NOT EDIT.
 *
 * Source of truth: press/protocol/protocol.toml
 * Regenerate:      pixi run gen-protocol
 * Verify:          pixi run gen-protocol --check
 */

#ifndef PROTOCOL_H_
#define PROTOCOL_H_

#include <stdint.h>

#define PROTOCOL_VERSION 1

/* ── Recoil pattern storage ─────────────────────────────── */
#define MAX_PATTERN_POINTS 300
#define PATTERN_POINT_SIZE 6

typedef struct {
    int16_t  dx;
    int16_t  dy;
    uint16_t t_ms;
} pattern_point_t;

/* ── Commands (PC → Pico over CDC) ──────────────────────── */
/* Every CMD_*_LEN counts the opcode byte, so it is the number of
 * bytes that must be buffered before the command can be parsed. */

/* Replace the stored recoil curve. Clamped to MAX_PATTERN_POINTS.
 * Then: count * PATTERN_POINT_SIZE more bytes (LEN below is the HEADER only).
 */
#define CMD_PATTERN_UPLOAD     0x10
#define CMD_PATTERN_UPLOAD_LEN 3

/* Drop the stored curve. Recoil compensation emits nothing until re-uploaded.
 */
#define CMD_PATTERN_CLEAR      0x11
#define CMD_PATTERN_CLEAR_LEN  1

/* Gate compensation without discarding the curve. This is the difference
 * between a run that measures RAW recoil and one that measures the residual.
 */
#define CMD_RECOIL_ENABLE      0x12
#define CMD_RECOIL_ENABLE_LEN  2

/* Add to the mouse accumulator; emitted on the next HID report.
 */
#define CMD_MOVE               0x13
#define CMD_MOVE_LEN           5

/* Hold `buttons` for `duration_ms`, starting now.
 */
#define CMD_CLICK              0x14
#define CMD_CLICK_LEN          4

/* Move now, then click after `delay_ms` for `duration_ms`. One command rather
 * than two so the gap is timed on the Pico, not across USB.
 */
#define CMD_MOVE_CLICK         0x15
#define CMD_MOVE_CLICK_LEN     10

/* Suppress the human's real left click; only injected clicks fire. Zeroes the
 * aim delta.
 */
#define CMD_AIM_MODE           0x16
#define CMD_AIM_MODE_LEN       2

/* Latest aim correction, sent by the PC once per frame.
 */
#define CMD_SET_DELTA          0x17
#define CMD_SET_DELTA_LEN      5

/* Tap a key on the Pico's second (keyboard) HID interface. `keycode` is a USB
 * HID usage ID, forwarded uninterpreted — see press/pico_mouse.py HID_KEY_*.
 */
#define CMD_KEY                0x18
#define CMD_KEY_LEN            4

/* Report the curve as STORED, plus the duration each bullet is spread over. A
 * readback exists because measuring the firmware through the game is a closed
 * loop: a systematic error in here gets absorbed into the fitted curve and the
 * residual comes out clean. Two real bugs lived behind a clean residual.
 * Reply: [pat] lines
 */
#define CMD_PATTERN_READ       0x19
#define CMD_PATTERN_READ_LEN   1

/* Run the real per-bullet maths `iters` times over the stored pattern and
 * report commanded-vs-emitted totals. Touches no HID output, so it runs on a
 * bench with no game — which is what makes it cheap enough for every flash.
 * Reply: [sim] line
 */
#define CMD_RECOIL_SIM         0x1A
#define CMD_RECOIL_SIM_LEN     3

/* The mouse's own answer to the polling-rate SET, verbatim and undecoded — the
 * decode is the thing in doubt.
 * Reply: [razer] line
 */
#define CMD_RAZER_READ         0x1B
#define CMD_RAZER_READ_LEN     1

/* Reboot into the ROM bootloader so flash.py can write a .uf2 without the
 * BOOTSEL button. ⚠ If the running firmware is already broken this will not
 * answer, and the board must be re-plugged with BOOTSEL held.
 */
#define CMD_REBOOT_BOOTSEL     0xFF
#define CMD_REBOOT_BOOTSEL_LEN 1

#endif  /* PROTOCOL_H_ */
